/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuInicio;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author zujeily
 */
public class LoginDeUsuarioInicio extends javax.swing.JFrame {
FondoLI LI= new FondoLI();
    /**
     * Creates new form LoginDeUsuarioInicio
     */
    public LoginDeUsuarioInicio() {
        this.setContentPane(LI);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoGJS = new javax.swing.JLabel();
        JSSmallLU = new javax.swing.JLabel();
        PassLU = new javax.swing.JLabel();
        IniSesLU = new javax.swing.JLabel();
        UsuaLU = new javax.swing.JLabel();
        IngreUFieldLU = new javax.swing.JTextField();
        PasswordFieldLU = new javax.swing.JPasswordField();
        EnterLU = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        EnterLU1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        LogoGJS.setIcon(new javax.swing.ImageIcon("/home/zujeily/Downloads/Cliente Servidor/personajes historia y proyecto Escape Saw info /JS.png")); // NOI18N

        JSSmallLU.setIcon(new javax.swing.ImageIcon("/home/zujeily/Downloads/Cliente Servidor/personajes historia y proyecto Escape Saw info /sawlogosmallLU.png")); // NOI18N

        PassLU.setFont(new java.awt.Font("Gayathri Thin", 1, 18)); // NOI18N
        PassLU.setForeground(new java.awt.Color(255, 0, 0));
        PassLU.setText("Contraseña");

        IniSesLU.setFont(new java.awt.Font("Gayathri Thin", 1, 24)); // NOI18N
        IniSesLU.setForeground(new java.awt.Color(255, 0, 0));
        IniSesLU.setText("INICIAR SESIÓN");

        UsuaLU.setFont(new java.awt.Font("Gayathri Thin", 1, 18)); // NOI18N
        UsuaLU.setForeground(new java.awt.Color(255, 0, 0));
        UsuaLU.setText("Usuario");

        IngreUFieldLU.setBackground(new java.awt.Color(0, 0, 0));
        IngreUFieldLU.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        IngreUFieldLU.setForeground(new java.awt.Color(255, 0, 0));
        IngreUFieldLU.setText(" Ingrese su usuario");
        IngreUFieldLU.setBorder(null);
        IngreUFieldLU.setCaretColor(new java.awt.Color(255, 0, 0));
        IngreUFieldLU.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        IngreUFieldLU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreUFieldLUActionPerformed(evt);
            }
        });

        PasswordFieldLU.setBackground(new java.awt.Color(0, 0, 0));
        PasswordFieldLU.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        PasswordFieldLU.setForeground(new java.awt.Color(255, 0, 0));
        PasswordFieldLU.setText("jPasswordField1");
        PasswordFieldLU.setBorder(null);
        PasswordFieldLU.setCaretColor(new java.awt.Color(255, 0, 0));

        EnterLU.setBackground(new java.awt.Color(0, 0, 0));
        EnterLU.setFont(new java.awt.Font("Gayathri Thin", 1, 18)); // NOI18N
        EnterLU.setForeground(new java.awt.Color(255, 0, 0));
        EnterLU.setText("Entrar");
        EnterLU.setOpaque(false);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        EnterLU1.setBackground(new java.awt.Color(0, 0, 0));
        EnterLU1.setFont(new java.awt.Font("Gayathri Thin", 1, 18)); // NOI18N
        EnterLU1.setForeground(new java.awt.Color(255, 0, 0));
        EnterLU1.setText("Usuario Nuevo");
        EnterLU1.setBorderPainted(false);
        EnterLU1.setOpaque(false);
        EnterLU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterLU1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PassLU, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordFieldLU, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsuaLU, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IngreUFieldLU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(EnterLU, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(EnterLU1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(LogoGJS, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JSSmallLU)
                .addGap(18, 18, 18)
                .addComponent(IniSesLU, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JSSmallLU, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IniSesLU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoGJS, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UsuaLU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IngreUFieldLU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(PassLU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordFieldLU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(EnterLU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnterLU1)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreUFieldLUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreUFieldLUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreUFieldLUActionPerformed

    private void EnterLU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterLU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterLU1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDeUsuarioInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDeUsuarioInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDeUsuarioInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDeUsuarioInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDeUsuarioInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterLU;
    private javax.swing.JButton EnterLU1;
    private javax.swing.JTextField IngreUFieldLU;
    private javax.swing.JLabel IniSesLU;
    private javax.swing.JLabel JSSmallLU;
    private javax.swing.JLabel LogoGJS;
    private javax.swing.JLabel PassLU;
    private javax.swing.JPasswordField PasswordFieldLU;
    private javax.swing.JLabel UsuaLU;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

     class FondoLI extends JPanel{
     private Image Logo;         

     @Override
     public void paint (Graphics imagen){
         
     Logo =new ImageIcon(getClass().getResource("/imagenes/ES.png")).getImage();
     imagen.drawImage(Logo, 0, 0, getWidth(), getHeight(), this);
     setOpaque(false);
     super.paint(imagen);
     }}

}
